pool:
  vmImage: 'VS2017-Win2016'
  
steps:
# PowerShell
# Run a PowerShell script on Windows, macOS, or Linux.
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: .\build.ps1 
    arguments: 
